@startuml

'title "Test 3 environments at once with mock cam"

cloud Cloud {
	package Github {
		(workflow) <- (repository) : issue closed
	}

	package UI {
		(workflow) -down-> (WebApp) : kick CI
		
	}
	package Docker_Container {
		  artifact "ML0"
		  (Jupyter\nnotebook')
	}
	collections "GPUs"
"ML0" -right-> (Jupyter\nnotebook')
(Jupyter\nnotebook') <-down-> GPUs
}

actor "developer" --left--> (repository) : submit changes

package Jetson_nano {
	rectangle {
		  artifact "ML1"
		  (Jupyter\nnotebook)
	}

"ML1" -right-> (Jupyter\nnotebook)
(Jupyter\nnotebook) <-down-> (GPU)
}

(WebApp) --down--> RPI : run acceptance test

package RPI {
	(IP address)
}

package MCU {
        artifact "ML2"
	ML2 -down-> (TinyML)
	(TinyML) <-down- (**mock** cam'') : input test images 
}

RPI <-down- MCU : USB


@enduml